config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  def updates_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_likes_counter
  def updates_like_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integar: true, greater_than_0r_qual_to: 0 }
  validates :comments_counter, numericality: { only_integar: true, greater_than_0r_qual_to: 0 }

  after_save :update_posts_counter
  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  before_validation :default_params

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integar: true, greater_than_0r_qual_to: 0 }

  def most_recent_post
    posts.order(created_at: :desc).limit(3)
  end

  def default_params
    self.posts_counter = 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/like_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])

    @like = current_user.likes.new(
      author_id: current_user.id,
      post_id: @post.id
    )

    if @like.save
      redirect_to user_post_path(current_user, @post)
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/post_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.all
  end

  def show
    @post = Post.create(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @post = Post.includes([:author]).where(author_id: params[:author_id])
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes([:author])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params[:id])
    respond_to do |format|
      format.html do
        if @post.save
          redirect_to user_post_path(current_user, @post), notice: 'Post was successfully created.'
        else
          render :new, status: 'Error: Post was not created.'
        end
      end
    end
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/user_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show
    @user = User.create(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

   <body>
    <main>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </main>
  </body>
</html>

app/views/posts/_add_comment.html.erb
<div>
  <%= form_with url: "/users/#{@post.author_id}/posts/#{@post.id}/comments", scope: :comment do |format| %>
    <div>
        <%= format.label :Enter_Comment %><br>
        <%= format.text_area :text, rows: 10, require: true %>
        <%= format.submit "Comment" %>
    </div>
    <% end %>
</div>

app/views/posts/index.html.erb
<p>Here is a list of posts for a given user</p>

<section>
    <div class= "container">
        <div class="user-img">
          <img src="<%= @user.photo %>">
        </div>

        <div class="details">
          <h1 class= "user-head"><%= @user.name %></h1>
          <p class="user-para">Number of posts: <%= @user.posts_counter || 0 %></p>
    </div>

  <% @user.most_recent_post.each do |post| %>
    <%= link_to user_post_path(@user, post) do %>
        <h2>Post: <%= post.id %></h2>
    <% end %>
        <p>post description: <span><%= post.text %></span></p>
      <div>
      <span>Numbers of comments: <%= post.comments_counter || 0 %></span>
      <span>Numbers of likes: <%= post.likes_counter || 0 %></span>
      </div>
        <% end %>
        <ul>
      <% @post.each do |rec| %>
      <li><%= rec.author.name %> : <%= rec.text %></li>
      <% end %>
      </ul>
    <button>Pagination</button>
</section>

app/views/posts/new.html.erb
<h1>Create New Post</h1>

<%= form_with model: @post, url: user_posts_path, method: :post, local: true do |f| %>
<div>
    <div>
    <%= f.label :Post_title, require: true %><br>
    <%= f.text_field :title %>
    </div>

    <div>
    <%= f.label :Enter_text %><br>
    <%= f.text_area :text, rows: 10, require: true %>
    </div>
    <% @post.errors.full_messages_for(:title).each do |message| %>
    <div><%= message %></div>
    <% end %>
    <div><%= f.submit "Create Post" %></div>
</div>
<% end %>

app/views/posts/show.html.erb
<h6>Here is a list of posts for a given user</h6>

<section>
<div>
<h1><%= @post.title %></h1>
<div>
  <span>Number of comments: <%= @post.comments_counter || 0 %></span>
  <span>Number of likes: <%= @post.likes_counter || 0 %></span>
</div>

<p>post description: <%= @post.text %></p>

</div>

<div class= "recents-comments">
<div>
        <%= form_with url: "/users/#{@post.author_id}/posts/#{@post.id}/likes", scope: :like do |f| %>
        <%= f.submit "Like" %>
        <% end %>
</div>

<% @post.recent_comments.each do |comment|%>
  <li>Username : <%= comment.text %>
  <% end %>
</div>
<ul>
<% @comments.each do |rec| %>
<li><%= rec.author.name %> : <%= rec.text %></li>
<% end %>
</ul>
<%= render 'add_comment'%>
<section>

app/views/users/index.html.erb
<% if current_user != nil %>
  <%= button_to 'Sign Out', destroy_user_session_path, method: :delete %>
<% end %>
<h1>Here is a lists of a given user</h1>

<section>
  <% @users.each do |user| %>
    <%= link_to user_path(user.id) do %>
      <div class= "container">
        <div class="user-img">
          <img src="<%= user.photo %>">
        </div>
        <div class="details">
          <h1 class= "user-head"><%= user.name %></h1>
          <p class="user-para">Number of posts: <%= user.posts_counter || 0 %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</section>

app/views/users/show.html.erb
<h3>Here is a list of posts for a given user</h3>

<section>
      <div class= "container">
        <div class="user-img">
          <img src="<%= @user.photo %>">
        </div>

        <div class="details">
          <h1 class= "user-head"><%= @user.name %></h1>
          <p class="user-para">Number of posts: <%= @user.posts_counter || 0 %></p>
          <div class="user-bio">
          <h3>Bio: </h3>
          <p><%= @user.bio %></p>
          </div>
        </div>
      </div>
    <div class="user-post">
    <% @user.most_recent_post.each do |post| %>
    <%= link_to user_post_path(@user, post.id) do %>
    <div class="post-container">
    <h2>Post: <% post.title %></h2>
    <p><%= post.text %></p>
    <div>
    <span>comments: <%= post.comments_counter || 0 %></span>
    <span>likes: <%= post.likes_counter || 0 %></span>
    </div>
    <div>
    <% end %>
    <% end %>
    <div>

    <button><%= link_to "See all posts", user_posts_path(@user) %></button>
</section>